import type { Metadata } from "next";

import { MSWComponent } from "@/mocks/MSWComponent";
import Menubar from "@/components/Menubar/Menubar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MSWComponent>
          <Menubar />
          {children}
        </MSWComponent>
      </body>
    </html>
  );
}
