import type { Metadata } from "next";
import "./globals.css";
import "@/mocks";
import { MSWComponent } from "@/mocks/MSWComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MSWComponent>{children}</MSWComponent>
      </body>
    </html>
  );
}
