name: Deploy to EC2

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 저장소에서 코드를 가져옵니다.
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Node.js를 설치합니다.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 프로젝트 종속성을 설치하고 빌드합니다.
      - name: Install Dependencies
        run: |
          npm install
          npm run build

      # 4. 배포 파일 압축
      - name: Archive Artifacts
        run: zip -r build.zip .next public package.json package-lock.json

      # 5. EC2로 업로드
      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: build.zip
          target: ~/app/

      # 6. EC2에서 배포 스크립트 실행
      - name: Install Dependencies on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 필요한 패키지들 설치
            sudo apt update
            sudo apt install -y unzip
            sudo apt install -y nodejs npm
            sudo npm install pm2 -g

      # 7. 배포 후 명령 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/app/
            unzip -o build.zip
            npm install --production
            pm2 restart all
